#+TITLE: OpenBSD Setup
#+CATEGORIES: devops
#+TAGS: devops, openbsd, security, development
#+DATE: 2018-08-22
#+DRAFT: true

In this post I will be going over how I setup my OpenBSD development/admin machine. To follow along you'll need an
OpenBSD machine or virtual machine. Head over to my [[{{< ref "/posts/install-openbsd" >}}][OpenBSD Installation]]
post if you need to install OpenBSD.

I will be using as much of the default install of OpenBSD as possible. Customizing and installing packages only where it makes sense.
The reason for this is to ensure that we are keeping the footprint as small as possible.

** Prerequisites

You need to have a system running OpenBSD 6.3 or later.

** Command



** SSH

OpenSSH is extremely powerful I will be doing a dedicated post for OpenSSH configuration. In the meantime I highly
recommend picking up [[https://amzn.to/2BuesMF][SSH Mastery]] by Michael W Lucas and reading it cover to cover.

*** Keys

Please create a secure key, worst case use RSA with 4096 bits. Ideally use ed21559. For more information on generating
a ssh key correct, read [[{{< ref "/posts/update-your-ssh-keys-now" >}}][Update Your SSH Keys Now]].

*** Agent

Add the following to your =~/.profile=

#+BEGIN_SRC shell
eval $(ssh-agent -s)
#+END_SRC

** GPG

*** Installation

#+BEGIN_SRC shell
doas pkg_add gpg2
#+END_SRC

*** Configuration

#+BEGIN_SRC shell
alias gpg='gpg2'
export GPG_TTY=$(tty)
#+END_SRC
